apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: example-http-template
  title: Example http Template
  description: An example template for the scaffolder that creates a simple Node.js service
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - url
        - user
        - apiToken
      properties:
        url:
          type: string
          title: URL
          description: The URL to make the HTTP request to
        user:
          type: string
          title: user
          description: The user of the HTTP request
        apiToken:
          type: string
          title: apiToken
          description: The apiToken of the HTTP request
  steps:
    - id: run-http-action
      name: Run HTTP Action
      action: jenkins:post:job
      input:
        url: ${{ parameters.url }}
        user: ${{ parameters.user }}
        apiToken: ${{ parameters.apiToken }}
